name: Daily EPIAS Data Fetch

on:
  schedule:
    - cron: '0 11 * * *'  # UTC 11:00 = Türkiye saatiyle 14:00
    - cron: '0 17 * * *'  # UTC 17:00 = Türkiye saatiyle 20:00
    - cron: '0 2 * * *' # UTC 02:00 = Türkiye saatiyle 05:00
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: |
        python epias_data.py
      env:
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        EPIAS_USERNAME: ${{ secrets.EPIAS_USERNAME }}
        EPIAS_PASSWORD: ${{ secrets.EPIAS_PASSWORD }}
