name: Daily Meteologica Data Fetch

on:
  schedule:
    - cron: '0 3 * * *'  # UTC 11:00 = Türkiye saatiyle 14:00
  workflow_dispatch:      # Elle de tetikleyebilmek için

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: |
        python meteologica_data.py
